### ISSUE TITLE
5 checkpoint file limitation

### ISSUE THREAD

**Issue by BestJuly** [carpedm20/DCGAN-tensorflow#218]
Hi, all. 
When I using this code to train my model, I find a weird problem about the checkpoint. I save the model every 10 epoch and after 200 epoch, I only find 5 model files. For example, when the training is run and I have got the model data for epoch 9,19,29,39,49. After epoch 59 is done, I will get model data for epoch 59 but the data for epoch 9 is missing. It seems that there is a limitation that I can only save 5 model data. I read the code several times but I can not find where the limitation lies. 
I only use tensorflow for only a short time so I'm not sure whether it is limited by tensorflow itself. Thank you for your answering.

**Comment by asispatra** [comment]
@BestJuly, This issue is related to Tensorflow tf.train.Saver()
In the [model.py#L143](https://github.com/carpedm20/DCGAN-tensorflow/blob/master/model.py#L143) line you change like this: 
`self.saver = tf.train.Saver(max_to_keep=5)`

Default value of checkpoint to keep is 5, you can change this value.

Reference: https://www.tensorflow.org/api_docs/python/tf/train/Saver

**Comment by BestJuly** [comment]
@asispatra Thank you very much. It seems that I need to read the official document and learn more details about the tensorflow.
