### ISSUE TITLE
"one pic error!..."  after Changing Batch Size

### ISSUE THREAD

**Issue by TigistAbebaw** [carpedm20/DCGAN-tensorflow#226]
I have a my own dataset of I changed the batch size to 32 , but it is unable to generate samples . do I have to change the samples image size. Or can u suggest me a solution. Thanks.

**Comment by Usernamezhx** [comment]
@TigistAbebaw  hi TigistAbebaw I have the problem too. it has nothing in the samples folder after i have finished one epoch.

**Comment by MihaiDogariu** [comment]
@TigistAbebaw @Usernamezhx 
Hi, this error is because of the fact that the batch size is not a square number. When it is trying to save the images it looks for a shape under which to store the images (as you can see in the demo it is an 8x8 square). The line which fails, if you trace it back, is the assertion from the `image_manifold_size` function, in the `utils.py` file. If `manifold_h * manifold_w` is different from `num_images` then you get that error.
One way to overcome this is to hardcode one of these values to something that you know it won't break. E.g. for batches which are a power of 2 and larger than 16:
```python
manifold_w = int(16) 
manifold_h = int(num_images/16)
```
Bare in mind that both values must be integers. Simply running `manifold_h = num_images/16`, without a cast, will result in an error.
